import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary":                    "#845400",
        "primary-container":          "#ffb347",
        "primary-fixed":              "#ffddb6",
        "primary-fixed-dim":          "#ffb95a",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "#704700",
        "on-primary-fixed":           "#2a1800",
        "on-primary-fixed-variant":   "#643f00",
        "inverse-primary":            "#ffb95a",
        "secondary":                  "#5f5e5e",
        "secondary-container":        "#e2dfde",
        "secondary-fixed":            "#e5e2e1",
        "secondary-fixed-dim":        "#c8c6c5",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "#636262",
        "on-secondary-fixed":         "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "tertiary":                   "#006780",
        "tertiary-container":         "#52d0f9",
        "tertiary-fixed":             "#b8eaff",
        "tertiary-fixed-dim":         "#58d5fe",
        "on-tertiary":                "#ffffff",
        "on-tertiary-container":      "#00576d",
        "on-tertiary-fixed":          "#001f28",
        "on-tertiary-fixed-variant":  "#004d61",
        "surface":                    "#f9f9f9",
        "surface-bright":             "#f9f9f9",
        "surface-dim":                "#dadada",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f3f3f3",
        "surface-container":          "#eeeeee",
        "surface-container-high":     "#e8e8e8",
        "surface-container-highest":  "#e2e2e2",
        "surface-variant":            "#e2e2e2",
        "surface-tint":               "#845400",
        "on-surface":                 "#1a1c1c",
        "on-surface-variant":         "#524535",
        "on-background":              "#1a1c1c",
        "inverse-surface":            "#2f3131",
        "inverse-on-surface":         "#f1f1f1",
        "outline":                    "#847463",
        "outline-variant":            "#d6c3b0",
        "background":                 "#f9f9f9",
        "error":                      "#ba1a1a",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "on-error-container":         "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "0.75rem",
        full:    "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body:     ["Inter",   "system-ui", "sans-serif"],
        label:    ["Inter",   "system-ui", "sans-serif"],
        sans:     ["Inter",   "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg":   ["3.5rem",  { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg":  ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md":  ["1.75rem", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm":  ["1.5rem",  { lineHeight: "1.3",  fontWeight: "600" }],
        "body-lg":      ["1rem",    { lineHeight: "1.6",  fontWeight: "400" }],
        "label-md":     ["0.75rem", { lineHeight: "1.4",  letterSpacing: "0.1em" }],
      },
      boxShadow: {
        "ambient":     "0px 20px 40px rgba(26, 28, 28, 0.06)",
        "ambient-lg": "0px 32px 64px rgba(26, 28, 28, 0.08)",
        "gold":        "0px 8px 24px rgba(132, 84, 0, 0.20)",
      },
      transitionTimingFunction: {
        "soft-drift": "cubic-bezier(0.2, 0, 0, 1)",
      },
      transitionDuration: {
        "600": "600ms",
      },
      backgroundImage: {
        "hero-gradient":   "linear-gradient(135deg, #845400 0%, #ffb347 100%)",
        "card-gold":       "linear-gradient(135deg, #ffddb6 0%, #ffb95a 100%)",
      },
      scale: {
        "102": "1.02",
      },
    },
  },
  plugins: [],
};

export default config;
